(define (cond-actions clause)
  (if (pair? (cdr clause))
      (if (eq? '=> (cadr clause))
          (cddr clause)
          (error "Invalid cond clause -- COND-ACTIONS" clause))
      (cdr clause)))
