(define (div-interval x y)
  (define (include-zero? interval)
    (or (= (lower-bound interval 0))
        (= (upper-bound interval 0))
        (and (< (lower-bound interval) 0) (> (upper-bound interval) 0))))
  (if (include-zero? y)
      (display "error")
      (mul-interval x
                    (make-interval (/ 1.0 (upper-bound y))
                                   (/ 1.0 (lower-bound y))))))
