(define (reverse items)
  (define (iter result next)
    (cond ((null? next) result)
          (else (iter (cons (car next) result) (cdr next)))))
  (if (null? items)
      ()
      (iter (cons (car items) ()) (cdr items))))
